name: Test EC2 SSH Connection

on:
  push:
    branches:
      - main  # Trigger on pushes to the development branch

jobs:
  test-ssh:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create .ssh directory and Save SSH Key (Setup)
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ls -l ~/.ssh

      - name: Test SSH Connection to EC2
        run: |
          echo "Testing SSH connection to EC2"
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ubuntu@${{ secrets.EC2_PUBLIC_IP }} "echo SSH connection successful"
